const { identity, normal, ones, zeros } = require("@jrc03c/js-math-tools")
const isBinary = require("./is-binary.js")

test("checks whether various things are binary", () => {
  expect(isBinary(0)).toBe(true)
  expect(isBinary(1)).toBe(true)
  expect(isBinary([0])).toBe(true)
  expect(isBinary([1])).toBe(true)
  expect(isBinary([0, 1])).toBe(true)
  expect(isBinary([1, 0])).toBe(true)
  expect(isBinary(zeros(1000))).toBe(true)
  expect(isBinary(ones(1000))).toBe(true)
  expect(isBinary(zeros(100).concat(ones(100)))).toBe(true)
  expect(isBinary(identity(100))).toBe(true)
  expect(isBinary(normal([5, 5, 5]))).toBe(false)
  expect(isBinary(123)).toBe(false)
  expect(isBinary("foo")).toBe(false)
  expect(isBinary(true)).toBe(false)
  expect(isBinary(false)).toBe(false)
  expect(isBinary(undefined)).toBe(false)
  expect(isBinary(null)).toBe(false)
  expect(isBinary(() => {})).toBe(false)
  expect(isBinary({})).toBe(false)
})
